DATA_PATH = "data"
DATA_GENERATED_PATH = f"{DATA_PATH}/generated"
RESULTS_PATH = "results"
RESULTS_FEATURES_PATH = f"{RESULTS_PATH}/features"

RESULTS_LINEAR_REGRESSION_PATH = f"{RESULTS_PATH}/linear-regression"
